import { useState, useEffect } from 'react';
import { Plus, Edit, Trash2, Eye, Download, Search, Building2, Phone, Mail, X, SlidersHorizontal, ArrowUpDown, MapPin, CreditCard, FileText, Truck, CheckCircle2 } from 'lucide-react';
import Layout from '../components/layout/Layout';
import Modal from '../components/common/Modal';
import ConfirmDialog from '../components/common/ConfirmDialog';
import SupplierForm from '../components/features/suppliers/SupplierForm';
import {
  getAllSuppliers,
  createSupplier,
  updateSupplier,
  deleteSupplier,
  getSupplierStats,
  exportSuppliers,
  generateSupplierCode
} from '../services/supplierService';
import { formatPhoneNumber } from '../utils/formatters';
import toast from 'react-hot-toast';
import * as XLSX from 'xlsx';

export default function Suppliers() {
  const [suppliers, setSuppliers] = useState([]);
  const [filteredSuppliers, setFilteredSuppliers] = useState([]);
  const [stats, setStats] = useState(null);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');

  // Auto-generated code for new supplier
  const [autoGeneratedCode, setAutoGeneratedCode] = useState('');

  // Filters
  const [filters, setFilters] = useState({
    status: '',
    sortBy: 'name-asc',
    hasEmail: '',
    hasPhone: '',
    itemsPerPage: 25
  });
  const [showFilters, setShowFilters] = useState(false);

  // Modal states
  const [showAddModal, setShowAddModal] = useState(false);
  const [showEditModal, setShowEditModal] = useState(false);
  const [showDetailModal, setShowDetailModal] = useState(false);
  const [showDeleteDialog, setShowDeleteDialog] = useState(false);
  const [selectedSupplier, setSelectedSupplier] = useState(null);
  const [formLoading, setFormLoading] = useState(false);

  useEffect(() => {
    loadSuppliers();
    loadStats();
  }, []);

  useEffect(() => {
    filterAndSortSuppliers();
  }, [searchQuery, filters, suppliers]);

  const loadSuppliers = async () => {
    try {
      setLoading(true);
      const data = await getAllSuppliers();
      setSuppliers(data);
    } catch (error) {
      toast.error('Gagal memuat data supplier');
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  const loadStats = async () => {
    try {
      const data = await getSupplierStats();
      setStats(data);
    } catch (error) {
      console.error(error);
    }
  };

  const filterAndSortSuppliers = () => {
    let result = [...suppliers];

    // Search filter
    if (searchQuery) {
      const query = searchQuery.toLowerCase();
      result = result.filter(s =>
        s.name.toLowerCase().includes(query) ||
        s.code.toLowerCase().includes(query) ||
        s.email?.toLowerCase().includes(query) ||
        s.phone?.toLowerCase().includes(query) ||
        s.address?.toLowerCase().includes(query)
      );
    }

    // Status filter
    if (filters.status === 'active') {
      result = result.filter(s => s.isActive);
    } else if (filters.status === 'inactive') {
      result = result.filter(s => !s.isActive);
    }

    // Email filter
    if (filters.hasEmail === 'yes') {
      result = result.filter(s => s.email && s.email.trim() !== '');
    } else if (filters.hasEmail === 'no') {
      result = result.filter(s => !s.email || s.email.trim() === '');
    }

    // Phone filter
    if (filters.hasPhone === 'yes') {
      result = result.filter(s => s.phone && s.phone.trim() !== '');
    } else if (filters.hasPhone === 'no') {
      result = result.filter(s => !s.phone || s.phone.trim() === '');
    }

    // Sort
    switch (filters.sortBy) {
      case 'name-asc':
        result.sort((a, b) => a.name.localeCompare(b.name));
        break;
      case 'name-desc':
        result.sort((a, b) => b.name.localeCompare(a.name));
        break;
      case 'code-asc':
        result.sort((a, b) => a.code.localeCompare(b.code));
        break;
      case 'code-desc':
        result.sort((a, b) => b.code.localeCompare(a.code));
        break;
      case 'newest':
        result.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
        break;
      case 'oldest':
        result.sort((a, b) => new Date(a.createdAt) - new Date(b.createdAt));
        break;
      default:
        break;
    }

    // Limit items per page
    result = result.slice(0, filters.itemsPerPage);

    setFilteredSuppliers(result);
  };

  const handleOpenAddModal = async () => {
    try {
      // Generate code before opening modal
      const code = await generateSupplierCode();
      setAutoGeneratedCode(code);
      setShowAddModal(true);
    } catch (error) {
      toast.error('Gagal generate kode supplier');
    }
  };

  const handleAdd = async (formData) => {
    try {
      setFormLoading(true);
      await createSupplier(formData);
      toast.success('Supplier berhasil ditambahkan');
      setShowAddModal(false);
      setAutoGeneratedCode('');
      loadSuppliers();
      loadStats();
    } catch (error) {
      toast.error(error.message || 'Gagal menambahkan supplier');
    } finally {
      setFormLoading(false);
    }
  };

  const handleEdit = async (formData) => {
    try {
      setFormLoading(true);
      await updateSupplier(selectedSupplier.id, formData);
      toast.success('Data supplier berhasil diperbarui');
      setShowEditModal(false);
      setSelectedSupplier(null);
      loadSuppliers();
      loadStats();
    } catch (error) {
      toast.error(error.message || 'Gagal memperbarui data supplier');
    } finally {
      setFormLoading(false);
    }
  };

  const handleDelete = async () => {
    try {
      setFormLoading(true);
      await deleteSupplier(selectedSupplier.id);
      toast.success('Supplier berhasil dihapus');
      setShowDeleteDialog(false);
      setSelectedSupplier(null);
      loadSuppliers();
      loadStats();
    } catch (error) {
      toast.error(error.message || 'Gagal menghapus supplier');
    } finally {
      setFormLoading(false);
    }
  };

  const handleExport = async () => {
    try {
      const data = await exportSuppliers({ status: filters.status });
      const ws = XLSX.utils.json_to_sheet(data);
      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, ws, 'Data Supplier');
      XLSX.writeFile(wb, `data-supplier-${new Date().toISOString().split('T')[0]}.xlsx`);
      toast.success('Data berhasil diexport');
    } catch (error) {
      toast.error('Gagal export data');
      console.error(error);
    }
  };

  const resetFilters = () => {
    setFilters({
      status: '',
      sortBy: 'name-asc',
      hasEmail: '',
      hasPhone: '',
      itemsPerPage: 25
    });
    setSearchQuery('');
  };

  const activeFilterCount = () => {
    let count = 0;
    if (filters.status) count++;
    if (filters.hasEmail) count++;
    if (filters.hasPhone) count++;
    if (filters.sortBy !== 'name-asc') count++;
    if (searchQuery) count++;
    return count;
  };

  return (
    <Layout>
      {/* Stats Cards */}
      {stats && (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8 mt-2">
          {/* Total Suppliers */}
          <div className="bg-white dark:bg-gray-800 rounded-xl p-5 border border-gray-200 dark:border-gray-700 shadow-sm">
            <div className="flex items-center justify-between mb-4">
              <div>
                <p className="text-sm text-gray-500 dark:text-gray-400 font-medium">Total Supplier</p>
                <h3 className="text-2xl font-bold text-gray-900 dark:text-white mt-1">{stats.total}</h3>
              </div>
              <div className="p-3 bg-blue-50 dark:bg-blue-900/20 rounded-xl">
                <Truck className="w-6 h-6 text-blue-600 dark:text-blue-400" />
              </div>
            </div>
            <p className="text-sm text-gray-600 dark:text-gray-400">
              Supplier terdaftar dalam sistem
            </p>
          </div>

          {/* Active Suppliers */}
          <div className="bg-white dark:bg-gray-800 rounded-xl p-5 border border-gray-200 dark:border-gray-700 shadow-sm">
            <div className="flex items-center justify-between mb-4">
              <div>
                <p className="text-sm text-gray-500 dark:text-gray-400 font-medium">Supplier Aktif</p>
                <h3 className="text-2xl font-bold text-gray-900 dark:text-white mt-1">{stats.active}</h3>
              </div>
              <div className="p-3 bg-green-50 dark:bg-green-900/20 rounded-xl">
                <CheckCircle2 className="w-6 h-6 text-green-600 dark:text-green-400" />
              </div>
            </div>
            <p className="text-sm text-green-600">
              Supplier aktif bertransaksi
            </p>
          </div>

          {/* Inactive Suppliers */}
          <div className="bg-white dark:bg-gray-800 rounded-xl p-5 border border-gray-200 dark:border-gray-700 shadow-sm">
            <div className="flex items-center justify-between mb-4">
              <div>
                <p className="text-sm text-gray-500 dark:text-gray-400 font-medium">Supplier Nonaktif</p>
                <h3 className="text-2xl font-bold text-gray-900 dark:text-white mt-1">{stats.inactive}</h3>
              </div>
              <div className="p-3 bg-gray-100 dark:bg-gray-700 rounded-xl">
                <Truck className="w-6 h-6 text-gray-500 dark:text-gray-400" />
              </div>
            </div>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              Supplier tidak aktif
            </p>
          </div>
        </div>
      )}

      {/* Toolbar */}
      <div className="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-100 dark:border-gray-700 px-6 py-4 mb-6">
        <div className="flex flex-col lg:flex-row gap-4">
          <div className="flex-1 relative">
            <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <Search className="w-5 h-5 text-gray-400" />
            </div>
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-10 pr-10 py-2.5 border border-gray-200 dark:border-gray-600 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100"
              placeholder="Cari nama, kode, email, atau telepon..."
            />
            {searchQuery && (
              <button
                onClick={() => setSearchQuery('')}
                className="absolute inset-y-0 right-0 pr-3 flex items-center hover:text-gray-600 dark:hover:text-gray-300 transition-colors"
              >
                <X className="w-4 h-4 text-gray-400" />
              </button>
            )}
          </div>

          <div className="flex gap-2 relative">
            <button
              onClick={() => setShowFilters(!showFilters)}
              className={`flex items-center gap-2 px-4 py-2.5 rounded-lg font-medium transition-colors relative whitespace-nowrap ${showFilters
                ? 'bg-blue-600 text-white'
                : 'bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 text-gray-700 dark:text-gray-300'
                }`}
            >
              <SlidersHorizontal className="w-4 h-4" />
              <span className="hidden sm:inline">Filter</span>
              {activeFilterCount() > 0 && (
                <span className="absolute -top-1 -right-1 w-5 h-5 bg-red-500 text-white text-xs rounded-full flex items-center justify-center">
                  {activeFilterCount()}
                </span>
              )}
            </button>

            <button
              onClick={handleExport}
              className="flex items-center gap-2 px-4 py-2.5 bg-green-600 hover:bg-green-700 text-white rounded-lg font-medium transition-colors whitespace-nowrap"
            >
              <Download className="w-4 h-4" />
              <span className="hidden sm:inline">Export</span>
            </button>

            <button
              onClick={handleOpenAddModal}
              className="flex items-center gap-2 px-4 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition-colors whitespace-nowrap"
            >
              <Plus className="w-4 h-4" />
              <span className="hidden sm:inline">Tambah Supplier</span>
            </button>
          </div>
        </div>

        {/* Advanced Filters */}
        {showFilters && (
          <div className="pt-4 mt-4 border-t border-gray-200 dark:border-gray-700 animate-in slide-in-from-top-2 duration-200">
            <div className="grid grid-cols-1 md:grid-cols-5 gap-3 mb-3">
              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">Status</label>
                <select
                  value={filters.status}
                  onChange={(e) => setFilters(prev => ({ ...prev, status: e.target.value }))}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-blue-500"
                >
                  <option value="">Semua Status</option>
                  <option value="active">Aktif</option>
                  <option value="inactive">Tidak Aktif</option>
                </select>
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">
                  <ArrowUpDown className="w-3 h-3 inline mr-1" />
                  Urutkan
                </label>
                <select
                  value={filters.sortBy}
                  onChange={(e) => setFilters(prev => ({ ...prev, sortBy: e.target.value }))}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-blue-500"
                >
                  <option value="name-asc">Nama (A-Z)</option>
                  <option value="name-desc">Nama (Z-A)</option>
                  <option value="code-asc">Kode (ASC)</option>
                  <option value="code-desc">Kode (DESC)</option>
                  <option value="newest">Terbaru</option>
                  <option value="oldest">Terlama</option>
                </select>
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">
                  <Mail className="w-3 h-3 inline mr-1" />
                  Email
                </label>
                <select
                  value={filters.hasEmail}
                  onChange={(e) => setFilters(prev => ({ ...prev, hasEmail: e.target.value }))}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-blue-500"
                >
                  <option value="">Semua</option>
                  <option value="yes">Ada Email</option>
                  <option value="no">Belum Ada Email</option>
                </select>
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">
                  <Phone className="w-3 h-3 inline mr-1" />
                  Telepon
                </label>
                <select
                  value={filters.hasPhone}
                  onChange={(e) => setFilters(prev => ({ ...prev, hasPhone: e.target.value }))}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-blue-500"
                >
                  <option value="">Semua</option>
                  <option value="yes">Ada Telepon</option>
                  <option value="no">Belum Ada Telepon</option>
                </select>
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">Tampilkan</label>
                <select
                  value={filters.itemsPerPage}
                  onChange={(e) => setFilters(prev => ({ ...prev, itemsPerPage: Number(e.target.value) }))}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-blue-500"
                >
                  <option value={10}>10 items</option>
                  <option value={25}>25 items</option>
                  <option value={50}>50 items</option>
                  <option value={100}>100 items</option>
                  <option value={1000}>Semua</option>
                </select>
              </div>
            </div>

            {activeFilterCount() > 0 && (
              <button
                onClick={resetFilters}
                className="flex items-center gap-2 px-3 py-1.5 bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 text-gray-700 rounded-lg text-sm font-medium transition-colors"
              >
                <X className="w-4 h-4" />
                Reset Filter ({activeFilterCount()})
              </button>
            )}
          </div>
        )}
      </div>

      {/* Table */}
      <div className="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-gray-50/50 dark:bg-gray-700/50 border-b border-gray-100 dark:border-gray-700">
              <tr>
                <th className="px-6 py-4 text-left text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider">Kode</th>
                <th className="px-6 py-4 text-left text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider">Nama Supplier</th>
                <th className="px-6 py-4 text-left text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider">Telepon</th>
                <th className="px-6 py-4 text-left text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider">Email</th>
                <th className="px-6 py-4 text-left text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider">Status</th>
                <th className="px-6 py-4 text-center text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider">Aksi</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100 dark:divide-gray-700">
              {loading ? (
                <tr>
                  <td colSpan="6" className="px-6 py-20 text-center">
                    <div className="flex flex-col items-center justify-center">
                      <div className="w-10 h-10 border-4 border-blue-600 border-t-transparent rounded-full animate-spin mb-4"></div>
                      <p className="text-gray-900 dark:text-white font-medium">Memuat data supplier...</p>
                    </div>
                  </td>
                </tr>
              ) : filteredSuppliers.length === 0 ? (
                <tr>
                  <td colSpan="6" className="px-6 py-20 text-center">
                    <div className="w-20 h-20 bg-gray-50 dark:bg-gray-700/50 rounded-full flex items-center justify-center mx-auto mb-6">
                      <Truck className="w-10 h-10 text-gray-300 dark:text-gray-500" />
                    </div>
                    <h3 className="text-lg font-bold text-gray-900 dark:text-white mb-2">Tidak ada supplier ditemukan</h3>
                    <p className="text-gray-500 dark:text-gray-400 max-w-sm mx-auto mb-6">
                      {searchQuery || activeFilterCount() > 0
                        ? 'Coba sesuaikan kata kunci pencarian atau filter Anda.'
                        : 'Belum ada data supplier. Tambahkan supplier baru untuk memulai.'}
                    </p>
                    {(searchQuery || activeFilterCount() > 0) ? (
                      <button
                        onClick={resetFilters}
                        className="px-6 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-xl font-medium transition-colors"
                      >
                        Reset Filter
                      </button>
                    ) : (
                      <button
                        onClick={handleOpenAddModal}
                        className="px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl font-medium shadow-lg shadow-blue-500/30 transition-all flex items-center gap-2 mx-auto"
                      >
                        <Plus size={18} />
                        Tambah Supplier
                      </button>
                    )}
                  </td>
                </tr>
              ) : (
                filteredSuppliers.map((supplier) => (
                  <tr key={supplier.id} className="group hover:bg-gray-50 dark:hover:bg-gray-700/50 transition-colors">
                    <td className="px-6 py-4">
                      <span className="font-mono text-xs font-medium bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300 px-2 py-1 rounded">
                        {supplier.code}
                      </span>
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-full bg-blue-50 dark:bg-blue-900/20 flex items-center justify-center text-blue-600 dark:text-blue-400 font-bold text-sm">
                          {supplier.name.charAt(0).toUpperCase()}
                        </div>
                        <div>
                          <p className="text-sm font-bold text-gray-900 dark:text-white">{supplier.name}</p>
                          {supplier.address && (
                            <p className="text-xs text-gray-500 line-clamp-1 max-w-[200px]">{supplier.address}</p>
                          )}
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-sm text-gray-600 dark:text-gray-300">
                      {supplier.phone ? (
                        <div className="flex items-center gap-2">
                          <Phone className="w-3.5 h-3.5 text-gray-400" />
                          {formatPhoneNumber(supplier.phone)}
                        </div>
                      ) : (
                        <span className="text-gray-400 italic text-xs">-</span>
                      )}
                    </td>
                    <td className="px-6 py-4 text-sm text-gray-600 dark:text-gray-300">
                      {supplier.email ? (
                        <div className="flex items-center gap-2">
                          <Mail className="w-3.5 h-3.5 text-gray-400" />
                          {supplier.email}
                        </div>
                      ) : (
                        <span className="text-gray-400 italic text-xs">-</span>
                      )}
                    </td>
                    <td className="px-6 py-4 text-sm">
                      <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium ${supplier.isActive
                        ? 'bg-green-50 text-green-700 border border-green-100 dark:bg-green-900/20 dark:text-green-400 dark:border-green-900'
                        : 'bg-gray-100 text-gray-600 border border-gray-200 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-600'
                        }`}>
                        <div className={`w-1.5 h-1.5 rounded-full ${supplier.isActive ? 'bg-green-500' : 'bg-gray-400'}`}></div>
                        {supplier.isActive ? 'Aktif' : 'Nonaktif'}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-center">
                      <div className="flex items-center justify-center gap-1">
                        <button
                          onClick={() => {
                            setSelectedSupplier(supplier);
                            setShowDetailModal(true);
                          }}
                          className="p-1.5 text-blue-600 hover:bg-blue-50 dark:hover:bg-blue-900/20 rounded transition-colors"
                          title="Lihat Detail"
                        >
                          <Eye className="w-4 h-4" />
                        </button>
                        <button
                          onClick={() => {
                            setSelectedSupplier(supplier);
                            setShowEditModal(true);
                          }}
                          className="p-1.5 text-amber-600 hover:bg-amber-50 dark:hover:bg-amber-900/20 rounded transition-colors"
                          title="Edit"
                        >
                          <Edit className="w-4 h-4" />
                        </button>
                        <button
                          onClick={() => {
                            setSelectedSupplier(supplier);
                            setShowDeleteDialog(true);
                          }}
                          className="p-1.5 text-red-600 hover:bg-red-50 dark:hover:bg-red-900/20 rounded transition-colors"
                          title="Hapus"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {filteredSuppliers.length > 0 && (
          <div className="px-6 py-4 border-t border-gray-100 dark:border-gray-700 bg-gray-50/50 dark:bg-gray-800/50 flex items-center justify-between">
            <p className="text-sm text-gray-500 dark:text-gray-400 font-medium">
              Menampilkan <span className="text-gray-900 dark:text-white font-semibold">{filteredSuppliers.length}</span> dari {suppliers.length} supplier
            </p>
          </div>
        )}
      </div>

      {/* Add Modal */}
      <Modal
        isOpen={showAddModal}
        onClose={() => {
          setShowAddModal(false);
          setAutoGeneratedCode('');
        }}
        title="Tambah Supplier Baru"
        size="lg"
      >
        <SupplierForm
          onSubmit={handleAdd}
          onCancel={() => {
            setShowAddModal(false);
            setAutoGeneratedCode('');
          }}
          loading={formLoading}
          autoGeneratedCode={autoGeneratedCode}
        />
      </Modal>

      {/* Edit Modal */}
      <Modal
        isOpen={showEditModal}
        onClose={() => {
          setShowEditModal(false);
          setSelectedSupplier(null);
        }}
        title="Edit Data Supplier"
        size="lg"
      >
        <SupplierForm
          supplier={selectedSupplier}
          onSubmit={handleEdit}
          onCancel={() => {
            setShowEditModal(false);
            setSelectedSupplier(null);
          }}
          loading={formLoading}
        />
      </Modal>

      {/* Detail Modal */}
      <Modal
        isOpen={showDetailModal}
        onClose={() => {
          setShowDetailModal(false);
          setSelectedSupplier(null);
        }}
        title="Detail Supplier"
        size="lg"
      >
        {selectedSupplier && (
          <div className="p-6">
            {/* Header Section */}
            <div className="flex items-start justify-between mb-6 pb-4 border-b">
              <div>
                <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-1">
                  {selectedSupplier.name}
                </h3>
                <p className="text-sm text-gray-500 dark:text-gray-300 font-mono">{selectedSupplier.code}</p>
              </div>
              <span className={`px-3 py-1.5 rounded-full text-xs font-semibold ${selectedSupplier.isActive
                ? 'bg-green-100 text-green-800 ring-2 ring-green-200'
                : 'bg-gray-100 dark:bg-gray-700 text-gray-800 ring-2 ring-gray-200'
                }`}>
                {selectedSupplier.isActive ? 'Aktif' : 'Tidak Aktif'}
              </span>
            </div>

            {/* Contact Information */}
            <div className="mb-6">
              <h4 className="text-sm font-semibold text-gray-700 uppercase tracking-wide mb-3">
                Informasi Kontak
              </h4>
              <div className="space-y-3">
                {selectedSupplier.phone && (
                  <div className="flex items-center gap-3 p-3 bg-gray-50 dark:bg-gray-700 rounded-lg">
                    <div className="flex-shrink-0">
                      <Phone className="w-5 h-5 text-blue-600" />
                    </div>
                    <div>
                      <p className="text-xs text-gray-500 dark:text-gray-300">Telepon</p>
                      <p className="text-sm font-medium text-gray-900 dark:text-white">
                        {formatPhoneNumber(selectedSupplier.phone)}
                      </p>
                    </div>
                  </div>
                )}

                {selectedSupplier.email && (
                  <div className="flex items-center gap-3 p-3 bg-gray-50 dark:bg-gray-700 rounded-lg">
                    <div className="flex-shrink-0">
                      <Mail className="w-5 h-5 text-purple-600" />
                    </div>
                    <div>
                      <p className="text-xs text-gray-500 dark:text-gray-300">Email</p>
                      <p className="text-sm font-medium text-gray-900 dark:text-white">
                        {selectedSupplier.email}
                      </p>
                    </div>
                  </div>
                )}

                {selectedSupplier.address && (
                  <div className="flex items-start gap-3 p-3 bg-gray-50 dark:bg-gray-700 rounded-lg">
                    <div className="flex-shrink-0 mt-0.5">
                      <MapPin className="w-5 h-5 text-red-600" />
                    </div>
                    <div>
                      <p className="text-xs text-gray-500 dark:text-gray-300">Alamat</p>
                      <p className="text-sm font-medium text-gray-900 dark:text-white leading-relaxed">
                        {selectedSupplier.address}
                      </p>
                    </div>
                  </div>
                )}
              </div>
            </div>

            {/* Bank Details - Highlighted Section */}
            {(selectedSupplier.bankName || selectedSupplier.bankAccount) && (
              <div className="mb-6">
                <div className="flex items-center gap-2 mb-3">
                  <CreditCard className="w-5 h-5 text-blue-600" />
                  <h4 className="text-sm font-semibold text-gray-700 uppercase tracking-wide">
                    Rekening Bank untuk Pembayaran
                  </h4>
                </div>

                <div className="bg-gradient-to-br from-blue-50 to-indigo-50 p-4 rounded-xl border-2 border-blue-200 shadow-sm">
                  <div className="space-y-3">
                    {selectedSupplier.bankName && (
                      <div className="flex justify-between items-center">
                        <span className="text-sm font-medium text-gray-600 dark:text-gray-300">Bank</span>
                        <span className="text-base font-bold text-gray-900 dark:text-white bg-white px-3 py-1 rounded-lg shadow-sm">
                          {selectedSupplier.bankName}
                        </span>
                      </div>
                    )}

                    {selectedSupplier.bankAccount && (
                      <div className="flex justify-between items-center">
                        <span className="text-sm font-medium text-gray-600 dark:text-gray-300">No. Rekening</span>
                        <div className="bg-white px-3 py-1 rounded-lg shadow-sm">
                          <span className="text-base font-semibold text-blue-700 tracking-wide">
                            {selectedSupplier.bankAccount}
                          </span>
                        </div>
                      </div>
                    )}

                    {selectedSupplier.bankAccountName && (
                      <div className="flex justify-between items-center">
                        <span className="text-sm font-medium text-gray-600 dark:text-gray-300">Atas Nama</span>
                        <span className="text-base font-semibold text-gray-900 dark:text-white bg-white px-3 py-1 rounded-lg shadow-sm">
                          {selectedSupplier.bankAccountName}
                        </span>
                      </div>
                    )}
                  </div>

                  {/* Copy Button for Bank Account */}
                  {selectedSupplier.bankAccount && (
                    <button
                      onClick={() => {
                        navigator.clipboard.writeText(selectedSupplier.bankAccount);
                        toast.success('Nomor rekening berhasil disalin!');
                      }}
                      className="mt-3 w-full flex items-center justify-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-sm font-medium transition-colors shadow-sm"
                    >
                      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                      </svg>
                      Salin Nomor Rekening
                    </button>
                  )}
                </div>
              </div>
            )}

            {/* Statistics Section (if available) */}
            {(selectedSupplier.totalOrders > 0 || selectedSupplier.totalAmount > 0) && (
              <div className="mb-6">
                <h4 className="text-sm font-semibold text-gray-700 uppercase tracking-wide mb-3">
                  Statistik Pembelian
                </h4>
                <div className="grid grid-cols-2 gap-3">
                  <div className="bg-gradient-to-br from-green-50 to-emerald-50 p-4 rounded-lg border border-green-200">
                    <p className="text-xs text-gray-600 dark:text-gray-300 mb-1">Total Transaksi</p>
                    <p className="text-2xl font-bold text-green-700">
                      {selectedSupplier.totalOrders || 0}
                    </p>
                  </div>
                  <div className="bg-gradient-to-br from-yellow-50 to-orange-50 p-4 rounded-lg border border-yellow-200">
                    <p className="text-xs text-gray-600 dark:text-gray-300 mb-1">Total Nilai</p>
                    <p className="text-2xl font-bold text-orange-700">
                      Rp {(selectedSupplier.totalAmount || 0).toLocaleString('id-ID')}
                    </p>
                  </div>
                </div>
                {selectedSupplier.lastOrderDate && (
                  <p className="text-xs text-gray-500 dark:text-gray-300 mt-2 text-center">
                    Transaksi terakhir: {new Date(selectedSupplier.lastOrderDate).toLocaleDateString('id-ID', {
                      day: 'numeric',
                      month: 'long',
                      year: 'numeric'
                    })}
                  </p>
                )}
              </div>
            )}

            {/* Notes Section */}
            {selectedSupplier.notes && (
              <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
                <div className="flex items-start gap-2">
                  <FileText className="w-5 h-5 text-yellow-600 flex-shrink-0 mt-0.5" />
                  <div>
                    <p className="text-xs font-semibold text-yellow-800 uppercase tracking-wide mb-1">
                      Catatan
                    </p>
                    <p className="text-sm text-gray-700 leading-relaxed">
                      {selectedSupplier.notes}
                    </p>
                  </div>
                </div>
              </div>
            )}

            {/* Action Buttons at Bottom */}
            <div className="flex gap-3 mt-6 pt-4 border-t">
              <button
                onClick={() => {
                  setShowDetailModal(false);
                  setShowEditModal(true);
                }}
                className="flex-1 flex items-center justify-center gap-2 px-4 py-2.5 bg-yellow-600 hover:bg-yellow-700 text-white rounded-lg font-medium transition-colors"
              >
                <Edit className="w-4 h-4" />
                Edit Supplier
              </button>
              <button
                onClick={() => {
                  setShowDetailModal(false);
                }}
                className="px-6 py-2.5 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 dark:bg-gray-700 font-medium transition-colors"
              >
                Tutup
              </button>
            </div>
          </div>
        )}
      </Modal>

      {/* Delete Confirmation */}
      <ConfirmDialog
        isOpen={showDeleteDialog}
        onClose={() => {
          setShowDeleteDialog(false);
          setSelectedSupplier(null);
        }}
        onConfirm={handleDelete}
        title="Hapus Supplier"
        message={`Apakah Anda yakin ingin menghapus supplier "${selectedSupplier?.name}"? Tindakan ini tidak dapat dibatalkan.`}
        type="danger"
        confirmText="Hapus"
        loading={formLoading}
      />
    </Layout>
  );
}