import { useState, useEffect } from 'react';
import { Building2, Phone, Mail, MapPin, FileText, AlertCircle, Check, Landmark } from 'lucide-react';
import { INDONESIA_BANKS } from '../../../config/constants';

export default function SupplierForm({ supplier, onSubmit, onCancel, loading, autoGeneratedCode }) {
  const [formData, setFormData] = useState({
    code: '',
    name: '',
    phone: '',
    email: '',
    address: '',
    bankName: '',
    bankAccount: '',
    bankAccountName: '',
    notes: '',
    isActive: true
  });

  const [errors, setErrors] = useState({});
  const [touched, setTouched] = useState({});

  // Set form data when editing or when auto-generated code is provided
  useEffect(() => {
    if (supplier) {
      setFormData({
        code: supplier.code || '',
        name: supplier.name || '',
        phone: supplier.phone || '',
        email: supplier.email || '',
        address: supplier.address || '',
        bankName: supplier.bankName || '',
        bankAccount: supplier.bankAccount || '',
        bankAccountName: supplier.bankAccountName || '',
        notes: supplier.notes || '',
        isActive: supplier.isActive !== undefined ? supplier.isActive : true
      });
    } else if (autoGeneratedCode) {
      setFormData(prev => ({
        ...prev,
        code: autoGeneratedCode
      }));
    }
  }, [supplier, autoGeneratedCode]);

  const validateField = (name, value) => {
    let error = '';

    switch (name) {
      case 'name':
        if (!value || !value.trim()) {
          error = 'Nama supplier wajib diisi';
        } else if (value.trim().length < 3) {
          error = 'Nama minimal 3 karakter';
        }
        break;

      case 'email':
        if (value && value.trim()) {
          const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
          if (!emailRegex.test(value)) {
            error = 'Format email tidak valid';
          }
        }
        break;

      case 'phone':
        if (value && value.trim()) {
          const phoneRegex = /^[0-9+\-\s()]{8,20}$/;
          if (!phoneRegex.test(value)) {
            error = 'Format nomor telepon tidak valid (8-20 digit)';
          }
        }
        break;

      case 'bankAccount':
        if (value && value.trim()) {
          const accountRegex = /^[0-9]{5,20}$/;
          if (!accountRegex.test(value)) {
            error = 'Nomor rekening harus 5-20 digit angka';
          }
        }
        break;
    }

    return error;
  };

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    const newValue = type === 'checkbox' ? checked : value;

    setFormData(prev => ({
      ...prev,
      [name]: newValue
    }));

    // Clear error when user types (better UX)
    if (errors[name]) {
      const error = validateField(name, newValue);
      setErrors(prev => ({
        ...prev,
        [name]: error
      }));
    }
  };

  const handleBlur = (e) => {
    const { name, value } = e.target;

    setTouched(prev => ({
      ...prev,
      [name]: true
    }));

    const error = validateField(name, value);
    setErrors(prev => ({
      ...prev,
      [name]: error
    }));
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    // Mark all fields as touched
    const allTouched = Object.keys(formData).reduce((acc, key) => {
      acc[key] = true;
      return acc;
    }, {});
    setTouched(allTouched);

    // Validate all required fields
    const newErrors = {};

    const nameError = validateField('name', formData.name);
    if (nameError) newErrors.name = nameError;

    const emailError = validateField('email', formData.email);
    if (emailError) newErrors.email = emailError;

    const phoneError = validateField('phone', formData.phone);
    if (phoneError) newErrors.phone = phoneError;

    const bankAccountError = validateField('bankAccount', formData.bankAccount);
    if (bankAccountError) newErrors.bankAccount = bankAccountError;

    // If there are errors, don't submit
    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
      return;
    }

    // Submit the form
    onSubmit(formData);
  };

  const hasErrors = Object.keys(errors).some(key => errors[key]);

  return (
    <form onSubmit={handleSubmit} className="flex flex-col h-full">
      {/* Form Content - Scrollable */}
      <div className="flex-1 overflow-y-auto p-6 space-y-5">

        {/* Kode Supplier */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            <Building2 className="w-4 h-4 inline mr-1" />
            Kode Supplier {!supplier && '(Auto-generate)'}
          </label>
          <input
            type="text"
            name="code"
            value={formData.code}
            disabled
            className="w-full px-4 py-2.5 border border-gray-300 rounded-lg bg-gray-50 text-gray-600 cursor-not-allowed font-mono"
            placeholder={supplier ? formData.code : 'SUP/XXX'}
          />
          <p className="text-xs text-gray-500 mt-1">
            Kode akan otomatis dibuat saat menyimpan
          </p>
        </div>

        {/* Nama Supplier - REQUIRED */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Nama Supplier <span className="text-red-500">*</span>
          </label>
          <input
            type="text"
            name="name"
            value={formData.name}
            onChange={handleChange}
            onBlur={handleBlur}
            className={`w-full px-4 py-2.5 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-colors ${touched.name && errors.name
                ? 'border-red-500 bg-red-50'
                : 'border-gray-300 hover:border-gray-400'
              }`}
            placeholder="Masukkan nama supplier"
            autoFocus
          />
          {touched.name && errors.name && (
            <p className="text-xs text-red-600 mt-1.5 flex items-center gap-1">
              <AlertCircle className="w-3 h-3" />
              {errors.name}
            </p>
          )}
        </div>

        {/* Nomor Telepon */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            <Phone className="w-4 h-4 inline mr-1" />
            Nomor Telepon
          </label>
          <input
            type="text"
            name="phone"
            value={formData.phone}
            onChange={handleChange}
            onBlur={handleBlur}
            className={`w-full px-4 py-2.5 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-colors ${touched.phone && errors.phone
                ? 'border-red-500 bg-red-50'
                : 'border-gray-300 hover:border-gray-400'
              }`}
            placeholder="08xx-xxxx-xxxx atau 021-xxxxxxx"
          />
          {touched.phone && errors.phone && (
            <p className="text-xs text-red-600 mt-1.5 flex items-center gap-1">
              <AlertCircle className="w-3 h-3" />
              {errors.phone}
            </p>
          )}
        </div>

        {/* Email */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            <Mail className="w-4 h-4 inline mr-1" />
            Email (Opsional)
          </label>
          <input
            type="email"
            name="email"
            value={formData.email}
            onChange={handleChange}
            onBlur={handleBlur}
            className={`w-full px-4 py-2.5 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-colors ${touched.email && errors.email
                ? 'border-red-500 bg-red-50'
                : 'border-gray-300 hover:border-gray-400'
              }`}
            placeholder="email@example.com"
          />
          {touched.email && errors.email && (
            <p className="text-xs text-red-600 mt-1.5 flex items-center gap-1">
              <AlertCircle className="w-3 h-3" />
              {errors.email}
            </p>
          )}
        </div>

        {/* Alamat Lengkap */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            <MapPin className="w-4 h-4 inline mr-1" />
            Alamat Lengkap
          </label>
          <textarea
            name="address"
            value={formData.address}
            onChange={handleChange}
            rows={3}
            className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent hover:border-gray-400 transition-colors resize-none"
            placeholder="Jl. Contoh No. 123, Kelurahan, Kecamatan, Kota, Provinsi"
          />
          <p className="text-xs text-gray-500 mt-1">
            Tulis alamat selengkap-lengkapnya termasuk kota dan provinsi
          </p>
        </div>

        {/* BANK DETAILS SECTION */}
        <div className="border-t pt-5 mt-2">
          <div className="flex items-center gap-2 mb-4">
            <Landmark className="w-5 h-5 text-blue-600" />
            <h3 className="text-base font-semibold text-gray-900">
              Informasi Rekening Bank
            </h3>
          </div>
          <p className="text-sm text-gray-600 mb-4">
            Isi data rekening supplier untuk memudahkan pembayaran. Data ini akan muncul saat Anda melakukan pembelian dari supplier ini.
          </p>

          <div className="space-y-4 bg-blue-50 p-4 rounded-lg border border-blue-100">
            {/* Bank Name */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Nama Bank
              </label>
              <select
                name="bankName"
                value={formData.bankName}
                onChange={handleChange}
                className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-white"
              >
                <option value="">Pilih Bank</option>
                {INDONESIA_BANKS.map(bank => (
                  <option key={bank} value={bank}>{bank}</option>
                ))}
              </select>
            </div>

            {/* Bank Account Number */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Nomor Rekening
              </label>
              <input
                type="text"
                name="bankAccount"
                value={formData.bankAccount}
                onChange={handleChange}
                onBlur={handleBlur}
                className={`w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent hover:border-gray-400 transition-colors bg-white ${touched.bankAccount && errors.bankAccount
                    ? 'border-red-500 bg-red-50'
                    : 'border-gray-300 hover:border-gray-400'
                  }`}
                placeholder="1234567890"
                maxLength={20}
              />
              {touched.bankAccount && errors.bankAccount && (
                <p className="text-xs text-red-600 mt-1.5 flex items-center gap-1">
                  <AlertCircle className="w-3 h-3" />
                  {errors.bankAccount}
                </p>
              )}
            </div>

            {/* Account Holder Name */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Nama Pemilik Rekening
              </label>
              <input
                type="text"
                name="bankAccountName"
                value={formData.bankAccountName}
                onChange={handleChange}
                className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent hover:border-gray-400 transition-colors bg-white"
                placeholder="Nama sesuai buku rekening"
              />
              <p className="text-xs text-gray-500 mt-1">
                Pastikan nama sesuai dengan yang tertera di buku rekening
              </p>
            </div>
          </div>
        </div>

        {/* Catatan */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            <FileText className="w-4 h-4 inline mr-1" />
            Catatan Tambahan
          </label>
          <textarea
            name="notes"
            value={formData.notes}
            onChange={handleChange}
            rows={3}
            className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent hover:border-gray-400 transition-colors resize-none"
            placeholder="Catatan penting tentang supplier ini, seperti produk unggulan, kualitas layanan, dll."
          />
        </div>

        {/* Status Aktif */}
        <div className="flex items-center gap-3 p-4 bg-gray-50 rounded-lg border border-gray-200">
          <input
            type="checkbox"
            id="isActive"
            name="isActive"
            checked={formData.isActive}
            onChange={handleChange}
            className="w-5 h-5 text-blue-600 border-gray-300 rounded focus:ring-blue-500 focus:ring-2 cursor-pointer"
          />
          <label htmlFor="isActive" className="text-sm font-medium text-gray-700 cursor-pointer select-none">
            Status Aktif
            <span className="block text-xs text-gray-500 font-normal mt-0.5">
              Hanya supplier aktif yang dapat dipilih saat pembelian
            </span>
          </label>
        </div>

      </div>

      {/* Form Actions - Fixed at bottom */}
      <div className="border-t border-gray-200 p-4 bg-gray-50">
        <div className="flex justify-between items-center">
          <div className="text-sm">
            {hasErrors && (
              <span className="text-red-600 flex items-center gap-1.5 font-medium">
                <AlertCircle className="w-4 h-4" />
                Periksa kembali form Anda
              </span>
            )}
          </div>

          <div className="flex gap-3">
            <button
              type="button"
              onClick={onCancel}
              disabled={loading}
              className="px-5 py-2.5 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Batal
            </button>

            <button
              type="submit"
              disabled={loading || hasErrors}
              className="px-6 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 shadow-sm hover:shadow"
            >
              {loading ? (
                <>
                  <div className="spinner w-4 h-4 border-2"></div>
                  <span>Menyimpan...</span>
                </>
              ) : (
                <>
                  <Check className="w-4 h-4" />
                  <span>{supplier ? 'Update' : 'Simpan'}</span>
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      <style>{`
        @keyframes spin {
          to { transform: rotate(360deg); }
        }
        .spinner {
          border-color: rgba(255, 255, 255, 0.3);
          border-top-color: white;
          border-radius: 50%;
          animation: spin 0.6s linear infinite;
        }
      `}</style>
    </form>
  );
}